# cross pre-build hooks
[target.aarch64-unknown-linux-gnu]
pre-build = [
    "./.github/setup-mold-ubuntu.sh",
    "apt-get install -y libgtk-3-dev libasound2-dev libfontconfig1-dev"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "./.github/setup-mold-ubuntu.sh",
    "apt-get install -y libgtk-3-dev libasound2-dev libfontconfig1-dev"
]

[target.x86_64-pc-windows-gnu]
pre-build = [
    "./.github/setup-mold-ubuntu.sh",
    "apt-get install -y libgtk-3-dev libasound2-dev libfontconfig1-dev"
]
