# cross pre-build hooks
[build]
pre-build = [
    "./afx/afx/.github/setup-mold-ubuntu.sh",
    "pwd",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y libgtk-3-dev libasound2-dev libfontconfig1-dev"
]

[target.aarch64-unknown-linux-gnu]

[target.x86_64-unknown-linux-gnu]

[target.x86_64-pc-windows-gnu]
